"""W69-01 融合 · 材料 3D 可视化适配器（吸收 avogadrolibs 的分子数据结构，BSD-3）

把 avogadrolibs 的「原子/键/分子」数据结构与 XYZ 输出吸收成本仓材料可视化入口。
有 PyAvogadro 时走真实渲染；无 PyAvogadro 时用 mock 降级（诚实标注 degraded=True）。

纯 numpy/stdlib（mock 路径），真实渲染经 `import avogadro` 接入。
"""
from __future__ import annotations

import numpy as np

try:  # 真实后端（可选依赖）
    import avogadro as _avogadro  # type: ignore
    HAS_AVOGADRO = True
except ImportError:  # mock 降级
    _avogadro = None
    HAS_AVOGADRO = False

__all__ = ["HAS_AVOGADRO", "Molecule"]


class Molecule:
    """分子：原子 + 键（avogadrolibs 式数据结构）。"""

    def __init__(self) -> None:
        self.atoms: list[tuple[str, tuple[float, float, float]]] = []
        self.bonds: list[tuple[int, int, int]] = []  # (i, j, order)

    def add_atom(self, element: str, xyz: tuple[float, float, float]) -> int:
        self.atoms.append((element, tuple(float(v) for v in xyz)))
        return len(self.atoms) - 1

    def add_bond(self, i: int, j: int, order: int = 1) -> None:
        self.bonds.append((int(i), int(j), int(order)))

    def to_xyz(self) -> str:
        """XYZ 文本（原子数 + 注释行 + 每原子一行）。"""
        lines = [str(len(self.atoms)), "generated by avogadro_viz (mock)"]
        for el, (x, y, z) in self.atoms:
            lines.append(f"{el} {x:.4f} {y:.4f} {z:.4f}")
        return "\n".join(lines)

    @property
    def degraded(self) -> bool:
        return not HAS_AVOGADRO


def render(mol: Molecule) -> str:
    """渲染分子：有 PyAvogadro 走真实渲染，否则返回 XYZ 作为 mock 渲染描述。"""
    if HAS_AVOGADRO:
        return f"rendered:{_avogadro.render(mol.atoms)}"  # 真实后端
    return mol.to_xyz()  # mock 降级：XYZ 文本
